credentials:
  usernames:
    admin:
      email: sanou.ezekiel226@gmail.com
      name: Sanou Ezekiel
      password: $2b$12$Rtb1tnugIpfmtBD.DTy9uOvt3ILrDDIcFVzqT8WmC9GGtl753QUM6 # To be replaced with hashed password
    Z_Benjamin:
      name: ZOUNGRANA Benjamin
      password: $2b$12$Rtb1tnugIpfmtBD.DTy9uOvt3ILrDDIcFVzqT8WmC9GGtl753QUM6 # To be replaced with hashed password
    M_Alase:
      name: MUHAIMINU Alasé
      password: $2b$12$y6Blxh0eOnJTZ5vQAiPDteUwmPwrGmLqoprRy48fJSlYfRAMGEMzu # To be replaced with hashed password
    S_Aziz:
      name: SAWADOGO Aziz
      password: $2b$12$UEK9Uma/MXovYn8yEMOkruUk3NFZMHcLgWLRGdS33IWiGcYe3JE/. # To be replaced with hashed password:
    L_Auguste:
      name: LANKOANDE Auguste
      password: $2b$12$ewIcZ3t5aVb/tULvSIqm7OwCyXY0O.01gNlBMVxoLcIsnAigK/3/C # To be replaced with hashed password
    K_Abzeta:
      name: KABORE Abzeta
      password: $2b$12$llx9AIER8bpov.VsdH6etOnd5ieDML/9V/LLL0sF2GaaHa5j86AZ2 # To be replaced with hashed password
    B_Moumini:
      name: BAMOGO Moumini
      password: $2b$12$IsLTlF/6Z3dvc8bOwa4aa.ZGyR948rjV5p9nR76F1Jj2/C.6279o. # To be replaced with hashed password
    K_Moussa:
      name: KABORE Moussa
      password: $2b$12$uNtXpV0MVgmF.BBXHByt4OjQMUxdNcxtMT2tVsUbnUnHRTRd4OW6y # To be replaced with hashed password
    H_Marius:
      name: HOUNGNIZAN Marius
      password: $2b$12$5EdlDmNWRqqBsu2tmZwSr.QuprqoHWUlDkDx5Wo4b9WIJfVayloiG # To be replaced with hashed password
    S_Salfo:
      name: SAWADOGO Salfo
      password: $2b$12$RJiSUQx7kGkwHNAmIlcf9eOqj9el5bB7V7.C1dC.MJNgNrnkYeHq. # To be replaced with hashed password
    K_Gjemilatou:
      name: KABRE Djémilatou
      password: $2b$12$UKcS5KlUygOWBs1/Lab0DuJGvL/fjOvqBKf/mp0fslUUw7g/TNsdq # To be replaced with hashed password
    L_Yemboido:
      name: LOMPO YEMBOIDO
      password: $2b$12$rWD/QFTvNI7p6Lrb1Xg8cOlWQnyFUTWBTTcBf6CJF1p4WrhpeomAu # To be replaced with hashed password
    N_Tiandjoa:
      name: NABA TIANDJOA
      password: $2b$12$05ku90XPYEcG5A1g64JUsOVm6NWQBkaN32R5xTIamiqtfRAAK.xae # To be replaced with hashed password
    C_Aoua:
      name: COULIBALY AOUA
      password: $2b$12$miucix06ngyV8zYmxyAwBOmQv401.mtmRsmIibygq2eR.EWqmCgEW # To be replaced with hashed password
    T_Dieudonne:
      name: TOE DIEUDONNE
      password: $2b$12$di.ujOUaIe2cQ4I7Q2Ovue2S4U5ypforP6KXDUuzCRsa27dogmO8O # To be replaced with hashed password
    S_Augustin:
      name: SENI N AUGUSTIN
      password: $2b$12$R6PHycu6j0guJyV7cUeKC.tm9j6HO5DXqD56oeQAfjabpJ6VlXYqC # To be replaced with hashed password
    K_Isaac:
      name: KAM SIE ISAAC
      password: $2b$12$d3Xg1RUb5tBTHTNQY7OniuS4G1Tc396Xg5oC8hyoXJuZrPCt3TbOS # To be replaced with hashed password
    K_Armel:
      name: KABORE ARMEL
      password: $2b$12$UvbtYP4yl69GntYPgNLEZeJfRcIderFfh4HKZgJPaBGmkMJ/K4VqS # To be replaced with hashed password
    

   
      

cookie:
  expiry_days: 30
  key: AAFTSS # Must be string
  name: amd_ssedev
preauthorized:
  emails:
  - kounadiad626@gmail.com